import os

def generate_report(target_ip, nmap_output, nuclei_output, msf_results, post_exploit_notes):
    os.makedirs("reports", exist_ok=True)
    report_file = "reports/attack_report.md"

    with open(report_file, "w") as f:
        f.write(f"# 🛡️ AutoPwn Framework Report\n")
        f.write(f"**Target IP:** `{target_ip}`\n\n")
        
        f.write("## 🔍 Phase 1: Nmap Scan Results\n")
        f.write("```\n")
        f.write(nmap_output.strip() + "\n")
        f.write("```\n\n")

        f.write("## 🧪 Phase 2: Nuclei Scan Results\n")
        f.write("```\n")
        f.write(nuclei_output.strip() + "\n")
        f.write("```\n\n")

        f.write("## 💣 Phase 3: Exploitation Summary\n")
        f.write("```\n")
        f.write(msf_results.strip() + "\n")
        f.write("```\n\n")

        f.write("## 🔓 Phase 4: Post-Exploitation Notes\n")
        f.write("```\n")
        f.write(post_exploit_notes.strip() + "\n")
        f.write("```\n\n")

        f.write("---\n")
        f.write("✅ **Report generated by AutoPwn Framework**\n")

    print(f"[+] Report generated: {report_file}")


